# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50e2f40956518cf7c5135a2e3799e989e8ea7d92363165f0b53a4bf9d31bff7c2323846d0aea2a5e9758db5e27cc655f6e7d88199bd2cc7f00e863a52d70ed70

test:
  secret_key_base: 665e40a444a5b78d66de6ec5971391b72ac5e632419b6ee582d47f6983aab1b50afb7cd730765d36541bef220a903d0d9b44d55e19714a9c4d9d95afa70d8054

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
